version: "3"

services:
  app:
    # image: anangm182/practice_docker
    build: ./
    command: npm run start
    container_name: practice_docker
    volumes:
      - ./:/practice_docker
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/practice_docker
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
