version: "3"

services:
  practice_docker:
    image: anangm182/practice_docker
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/practice_docker
      - PORT=${PORT}
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
