version: "2"

services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    links:
      - db:db
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/practice_docker
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
